# Generated by Django 4.1 on 2022-09-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papaya', '0002_rename_created_brands_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
